# Generated by Django 4.1.3 on 2022-11-25 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("helix", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="helix.question",
            ),
        ),
    ]
